name: CI

on: [push]

jobs:
  windows-clang:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-llvm
          mingw-w64-x86_64-lld
          mingw-w64-x86_64-clang
    - uses: actions/checkout@v2
    - run: git clone https://github.com/Il-Capitano/cppb.git
    - run: ls
    - run: |
        cd cppb
        ls
        make
        cd ..
    - run: cppb/bin/cppb build
    - run: cppb/bin/cppb run
    - run: cppb/bin/cppb build --build-config test
    - run: cppb/bin/cppb run --build-config test
