name: CI

on: [push]

jobs:
  windows-clang:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          git
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-fmt
          mingw-w64-x86_64-rapidjson
          mingw-w64-x86_64-llvm
          mingw-w64-x86_64-lld
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-dwarfstack
          mingw-w64-x86_64-python
    - uses: actions/checkout@v2
    - run: git clone https://github.com/Il-Capitano/cppb.git
    - name: Build cppb
      run: |
        cd cppb
        mkdir bin
        make
        cd ..
    - run: touch ryu_format.ll
    - name: Build bozon
      run: cppb/bin/cppb build -v
    - name: Compile bitcode_test.bz
      run: cppb/bin/cppb run -v
    - name: Build tests
      run: cppb/bin/cppb build -v --build-config test
    - name: Run tests
      run: |
        cppb/bin/cppb run -v --build-config test
        cppb/bin/cppb run-rule run-tests
    - name: Compile ryu_format.bz
      run: cppb/bin/cppb run-rule ryu_format.ll -f
  windows-gcc:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          git
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-fmt
          mingw-w64-x86_64-rapidjson
          mingw-w64-x86_64-llvm
          mingw-w64-x86_64-lld
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-dwarfstack
          mingw-w64-x86_64-python
    - uses: actions/checkout@v2
    - name: Build cppb
      run: |
        git clone https://github.com/Il-Capitano/cppb.git
        cd cppb
        mkdir bin
        make
        cd ..
    - run: touch ryu_format.ll
    - name: Build bozon
      run: cppb/bin/cppb build -v --build-config gcc
    - name: Compile bitcode_test.bz
      run: cppb/bin/cppb run -v --build-config gcc
    - name: Build tests
      run: cppb/bin/cppb build -v --build-config test-gcc
    - name: Run tests
      run: cppb/bin/cppb run -v --build-config test-gcc
    - name: Compile ryu_format.bz
      run: cppb/bin/cppb run-rule ryu_format.gcc.ll -f
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        printf "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-focal-15.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt update
        sudo apt install gcc gcc-10 g++-10 llvm-15 lld-15 clang-15 libfmt-dev rapidjson-dev python3
    - name: Install libbacktrace
      run: |
        git clone https://github.com/ianlancetaylor/libbacktrace.git
        cd libbacktrace
        ./configure
        sudo make install
        cd ..
    - name: Build cppb
      run: |
        git clone https://github.com/Il-Capitano/cppb.git
        cd cppb
        mkdir bin
        make CXX=clang++-15 LD=lld-15
        cd ..
    - run: touch ryu_format.linux.ll
    - name: Build bozon
      run: cppb/bin/cppb build -v
    - name: Compile bitcode_test.bz
      run: cppb/bin/cppb run -v
    - name: Build tests
      run: cppb/bin/cppb build -v --build-config test
    - name: Run tests
      run: |
        cppb/bin/cppb run -v --build-config test
        cppb/bin/cppb run-rule run-tests
    - name: Compile ryu_format.bz
      run: cppb/bin/cppb run-rule ryu_format.linux.ll -f
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        printf "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-focal-15.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt update
        sudo apt install gcc lld gcc-10 g++-10 llvm-15 lld-15 clang-15 libfmt-dev rapidjson-dev python3
    - name: Install libbacktrace
      run: |
        git clone https://github.com/ianlancetaylor/libbacktrace.git
        cd libbacktrace
        ./configure
        sudo make install
        cd ..
    - name: Build cppb
      run: |
        git clone https://github.com/Il-Capitano/cppb.git
        cd cppb
        mkdir bin
        make CXX=clang++-15 LD=lld-15
        cd ..
    - run: touch ryu_format.linux.ll
    - name: Build bozon
      run: cppb/bin/cppb build -v --build-config gcc
    - name: Compile bitcode_test.bz
      run: cppb/bin/cppb run -v --build-config gcc
    - name: Build tests
      run: cppb/bin/cppb build -v --build-config test-gcc
    - name: Run tests
      run: cppb/bin/cppb run -v --build-config test-gcc
    - name: Compile ryu_format.bz
      run: cppb/bin/cppb run-rule ryu_format.linux.gcc.ll -f
